version: '2'

services:
  server:
    build: server/
    command: python server.py
    ports:
      - 5000:5000
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    
volumes:
  db-data: